// Instructions recognized by instruction extractor

// Keep in sync with
// https://raw.githubusercontent.com/radixdlt/radixdlt-scrypto/develop/transaction/src/model/instruction.rs
#[repr(u8)]
#[derive(Copy, Clone, Eq, PartialEq, Debug)]
pub enum Instruction {
    TakeFromWorktop,               //{ resource_address: ResourceAddress, },
    TakeFromWorktopByAmount,       // { amount: Decimal, resource_address: ResourceAddress, },
    TakeFromWorktopByIds, // { ids: BTreeSet<NonFungibleLocalId>, resource_address: ResourceAddress, },
    ReturnToWorktop,      // { bucket_id: ManifestBucket, },
    AssertWorktopContains, // { resource_address: ResourceAddress, },
    AssertWorktopContainsByAmount, // { amount: Decimal, resource_address: ResourceAddress, },
    AssertWorktopContainsByIds, // { ids: BTreeSet<NonFungibleLocalId>, resource_address: ResourceAddress, },
    PopFromAuthZone,
    PushToAuthZone, // { proof_id: ManifestProof, },
    ClearAuthZone,
    CreateProofFromAuthZone, // { resource_address: ResourceAddress, },
    CreateProofFromAuthZoneByAmount, // { amount: Decimal, resource_address: ResourceAddress, },
    CreateProofFromAuthZoneByIds, // { ids: BTreeSet<NonFungibleLocalId>, resource_address: ResourceAddress, },
    CreateProofFromBucket,        // { bucket_id: ManifestBucket, },
    CloneProof,                   // { proof_id: ManifestProof, },
    DropProof,                    // { proof_id: ManifestProof, },
    DropAllProofs,
    PublishPackage, // { code: ManifestBlobRef, abi: ManifestBlobRef, royalty_config: BTreeMap<String, RoyaltyConfig>, metadata: BTreeMap<String, String>, access_rules: AccessRules, },
    PublishPackageWithOwner, // { code: ManifestBlobRef, abi: ManifestBlobRef, owner_badge: NonFungibleGlobalId, },
    BurnResource,            // { bucket_id: ManifestBucket, },
    RecallResource,          // { vault_id: VaultId, amount: Decimal, },
    SetMetadata,             // { entity_address: GlobalAddress, key: String, value: String, },
    SetPackageRoyaltyConfig, // { package_address: PackageAddress, royalty_config: BTreeMap<String, RoyaltyConfig>, },
    SetComponentRoyaltyConfig, // { component_address: ComponentAddress, royalty_config: RoyaltyConfig, },
    ClaimPackageRoyalty,       // { package_address: PackageAddress, },
    ClaimComponentRoyalty,     // { component_address: ComponentAddress, },
    SetMethodAccessRule, // { entity_address: GlobalAddress, index: u32, key: AccessRuleKey, rule: AccessRule, },
    MintFungible,        // { resource_address: ResourceAddress, amount: Decimal, },
    MintNonFungible, // { resource_address: ResourceAddress, entries: BTreeMap<NonFungibleLocalId, (Vec<u8>, Vec<u8>)>, },
    MintUuidNonFungible, // { resource_address: ResourceAddress, entries: Vec<(Vec<u8>, Vec<u8>)>, },
    CreateFungibleResource, // { divisibility: u8, metadata: BTreeMap<String, String>, access_rules: BTreeMap<ResourceMethodAuthKey, (AccessRule, AccessRule)>, initial_supply: Option<Decimal>, },
    CreateFungibleResourceWithOwner, // { divisibility: u8, metadata: BTreeMap<String, String>, owner_badge: NonFungibleGlobalId, initial_supply: Option<Decimal>, },
    CreateNonFungibleResource, // { id_type: NonFungibleIdType, metadata: BTreeMap<String, String>, access_rules: BTreeMap<ResourceMethodAuthKey, (AccessRule, AccessRule)>, initial_supply: Option<BTreeMap<NonFungibleLocalId, (Vec<u8>, Vec<u8>)>>, },
    CreateNonFungibleResourceWithOwner, // { id_type: NonFungibleIdType, metadata: BTreeMap<String, String>, owner_badge: NonFungibleGlobalId, initial_supply: Option<BTreeMap<NonFungibleLocalId, (Vec<u8>, Vec<u8>)>>, },
    CreateAccessController, // { controlled_asset: ManifestBucket, primary_role: AccessRule, recovery_role: AccessRule, confirmation_role: AccessRule, timed_recovery_delay_in_minutes: Option<u32>, },
    CreateIdentity,         // { access_rule: AccessRule, },
    CallFunction, // { package_address: PackageAddress, blueprint_name: String, function_name: String, args: Vec<u8>, },
    CallMethod,   // { component_address: ComponentAddress, method_name: String, args: Vec<u8>, },
}

pub fn to_instruction(input: u8) -> Option<Instruction> {
    match input {
        0 => Some(Instruction::TakeFromWorktop),
        1 => Some(Instruction::TakeFromWorktopByAmount),
        2 => Some(Instruction::TakeFromWorktopByIds),
        3 => Some(Instruction::ReturnToWorktop),
        4 => Some(Instruction::AssertWorktopContains),
        5 => Some(Instruction::AssertWorktopContainsByAmount),
        6 => Some(Instruction::AssertWorktopContainsByIds),
        7 => Some(Instruction::PopFromAuthZone),
        8 => Some(Instruction::PushToAuthZone),
        9 => Some(Instruction::ClearAuthZone),
        10 => Some(Instruction::CreateProofFromAuthZone),
        11 => Some(Instruction::CreateProofFromAuthZoneByAmount),
        12 => Some(Instruction::CreateProofFromAuthZoneByIds),
        13 => Some(Instruction::CreateProofFromBucket),
        14 => Some(Instruction::CloneProof),
        15 => Some(Instruction::DropProof),
        16 => Some(Instruction::DropAllProofs),
        17 => Some(Instruction::PublishPackage),
        18 => Some(Instruction::PublishPackageWithOwner),
        19 => Some(Instruction::BurnResource),
        20 => Some(Instruction::RecallResource),
        21 => Some(Instruction::SetMetadata),
        22 => Some(Instruction::SetPackageRoyaltyConfig),
        23 => Some(Instruction::SetComponentRoyaltyConfig),
        24 => Some(Instruction::ClaimPackageRoyalty),
        25 => Some(Instruction::ClaimComponentRoyalty),
        26 => Some(Instruction::SetMethodAccessRule),
        27 => Some(Instruction::MintFungible),
        28 => Some(Instruction::MintNonFungible),
        29 => Some(Instruction::MintUuidNonFungible),
        30 => Some(Instruction::CreateFungibleResource),
        31 => Some(Instruction::CreateFungibleResourceWithOwner),
        32 => Some(Instruction::CreateNonFungibleResource),
        33 => Some(Instruction::CreateNonFungibleResourceWithOwner),
        34 => Some(Instruction::CreateAccessController),
        35 => Some(Instruction::CreateIdentity),
        36 => Some(Instruction::CallFunction),
        37 => Some(Instruction::CallMethod),
        _ => None,
    }
}
